### ISSUE TITLE
Undo of damage to actor with initially negative HP

### ISSUE THREAD

**Issue by skepickle** [cs96and/FoundryVTT-damage-log#5]
Foundry Virtual Tabletop version 0.8.8
System: 3.5 SRD version 0.94.5
Damage Log version 1.1.0
So here's a situation. Actor has -14 HP initially. I apply 1 dmg, taking it down to -15 HP. Then undo that damage using right-click on Damage Log entry. The actor now has 0 HP. Here's a screenshot that I believe captures the situation:
![negHPbug](https://user-images.githubusercontent.com/3783101/126573612-d71af04f-7361-4ebe-91f4-05bffbd5fb72.JPG)

**Comment by cs96and** [comment]
I am unfamiliar with D&D 3.5.  What does negative HP mean?

Anyway, Damage Log currently prevents you reducing HP past zero.  Should be easy enough to fix.

**Comment by skepickle** [comment]
Negative HP in 3.5e is not really different from positive HP. In 3.5e there is a negative HP threshold at which things actually die. There's no "Death Saving Throws" in 3.5e. Anyways... In my imagination, undoing damage should be agnostic to this right? It should just go back to the previous HP value if I undo the damage.

**Comment by cs96and** [comment]
I've been playing with the D&D v3.5 system, and I noticed that it is actually possible to reduce the HP of an actor below its minimum value.  E.g. the min HP for an Ape is -100, but you can reduce it to e.g. -200 if you wanted to.  I *think* this is a bug in the 3.5 system, but am happy to be corrected, because as I said, I don't know anything about v3.5.

Damage Log will try to cap values to the min and max values when reverting/redoing damage.  Should I continue to cap to the minimum value for 3.5?  Or should I allow it to go below that?

**Comment by cs96and** [comment]
Looks to be the same in PF1 as well.

**Comment by cs96and** [comment]
537c441831760292ec961c58fa1ca855b61ed2e4

**Comment by cs96and** [comment]
Fixed in v1.2.0
